#!/bin/bash
# Usage: S3KEY=abcde S3SECRET=1234 BUCKET=mybucket configure

function showusage {
cat <<EOF
NAME
   configure - configure jenkins for secret upload

SYNOPSIS
   S3KEY=abcde S3SECRET=1234 BUCKET=mybucket configure
DESCRIPTION
   Installs the S3 key, secret and bucket passed via environment variables into a volume container.
   Required for simplesecrets to be able to upload files.
RETURN VALUE
   0   - success
   1   - error
   3   - no change

EOF
   exit 1
}

[ -v S3KEY ] || { echo "Missing S3KEY." ; showusage ; }
[ -v S3SECRET ] || { echo "Missing S3SECRET." ; showusage ; }
[ -v BUCKET ] || { echo "Missing BUCKET." ; showusage ; }

TEMPFILE="/tmp/upload.sh"
TARGET="/config/upload.sh"

cat <<EOF >${TEMPFILE}
# S3 configuration
S3KEY=${S3KEY}
S3SECRET=${S3SECRET}
BUCKET=${BUCKET}
EOF

diff ${TEMPFILE} ${TARGET} >/dev/null 2>&1
if [ $? -eq 0 ]; then
   rm ${TEMPFILE}
   echo "S3 configuration unchanged."
   exit 3
fi

mv ${TEMPFILE} ${TARGET}
echo "S3 configuration updated."

#if [ ! -e /var/jenkins_home/configured ]; then
#   cp -a /tocopy/* /var
#fi

exit 0
