version: '2'

services:
   djenkins:
      image: j842/djenkins
      volumes:
         - "jenkins_home:/var/jenkins_home"
      ports:
         - "8080:8080"
         - "50000:50000"
      restart: always
      network_mode: "bridge"

volumes:
   jenkins_home:
      external:
         name: "drunner-${SERVICENAME}-varjenkins_home"
